const DIAGNOSTIC_CODE_VALUES = {
  AP_FALSE_INTERSECTION_APPROX: 'AP_FALSE_INTERSECTION_APPROX',
  AP_FALSE_UNSAFE_PATTERN: 'AP_FALSE_UNSAFE_PATTERN',
  NAME_AUTOMATON_COMPLEXITY_CAPPED: 'NAME_AUTOMATON_COMPLEXITY_CAPPED',
  NAME_AUTOMATON_BFS_APPLIED: 'NAME_AUTOMATON_BFS_APPLIED',
  NAME_AUTOMATON_BEAM_APPLIED: 'NAME_AUTOMATON_BEAM_APPLIED',
  AJV_FLAGS_MISMATCH: 'AJV_FLAGS_MISMATCH',
  ALLOF_SIMPLIFICATION_SKIPPED_UNEVALUATED:
    'ALLOF_SIMPLIFICATION_SKIPPED_UNEVALUATED',
  ANYOF_SIMPLIFICATION_SKIPPED_UNEVALUATED:
    'ANYOF_SIMPLIFICATION_SKIPPED_UNEVALUATED',
  COMPLEXITY_CAP_SCHEMA_SIZE: 'COMPLEXITY_CAP_SCHEMA_SIZE',
  COMPLEXITY_CAP_ANYOF: 'COMPLEXITY_CAP_ANYOF',
  COMPLEXITY_CAP_CONTAINS: 'COMPLEXITY_CAP_CONTAINS',
  COMPLEXITY_CAP_ENUM: 'COMPLEXITY_CAP_ENUM',
  COMPLEXITY_CAP_ONEOF: 'COMPLEXITY_CAP_ONEOF',
  COMPLEXITY_CAP_PATTERNS: 'COMPLEXITY_CAP_PATTERNS',
  CONTAINS_BAG_COMBINED: 'CONTAINS_BAG_COMBINED',
  CONTAINS_NEED_MIN_GT_MAX: 'CONTAINS_NEED_MIN_GT_MAX',
  CONTAINS_UNSAT_BY_SUM: 'CONTAINS_UNSAT_BY_SUM',
  DEFS_TARGET_MISSING: 'DEFS_TARGET_MISSING',
  DEPENDENCY_GUARDED: 'DEPENDENCY_GUARDED',
  DYNAMIC_PRESENT: 'DYNAMIC_PRESENT',
  DYNAMIC_SCOPE_BOUNDED: 'DYNAMIC_SCOPE_BOUNDED',
  EVALTRACE_PROP_SOURCE: 'EVALTRACE_PROP_SOURCE',
  EXCLMAX_IGNORED_NO_MAX: 'EXCLMAX_IGNORED_NO_MAX',
  EXCLMIN_IGNORED_NO_MIN: 'EXCLMIN_IGNORED_NO_MIN',
  EXCLUSIVITY_TWEAK_STRING: 'EXCLUSIVITY_TWEAK_STRING',
  EXTERNAL_REF_UNRESOLVED: 'EXTERNAL_REF_UNRESOLVED',
  EXTERNAL_REF_STUBBED: 'EXTERNAL_REF_STUBBED',
  RESOLVER_STRATEGIES_APPLIED: 'RESOLVER_STRATEGIES_APPLIED',
  RESOLVER_CACHE_HIT: 'RESOLVER_CACHE_HIT',
  RESOLVER_CACHE_MISS_FETCHED: 'RESOLVER_CACHE_MISS_FETCHED',
  RESOLVER_OFFLINE_UNAVAILABLE: 'RESOLVER_OFFLINE_UNAVAILABLE',
  RESOLVER_ADD_SCHEMA_SKIPPED_INCOMPATIBLE_DIALECT:
    'RESOLVER_ADD_SCHEMA_SKIPPED_INCOMPATIBLE_DIALECT',
  RESOLVER_ADD_SCHEMA_SKIPPED_DUPLICATE_ID:
    'RESOLVER_ADD_SCHEMA_SKIPPED_DUPLICATE_ID',
  RESOLVER_SNAPSHOT_APPLIED: 'RESOLVER_SNAPSHOT_APPLIED',
  RESOLVER_SNAPSHOT_LOAD_FAILED: 'RESOLVER_SNAPSHOT_LOAD_FAILED',
  RESOLVER_SNAPSHOT_FINGERPRINT_MISMATCH:
    'RESOLVER_SNAPSHOT_FINGERPRINT_MISMATCH',
  IF_AWARE_HINT_APPLIED: 'IF_AWARE_HINT_APPLIED',
  IF_AWARE_HINT_SKIPPED_INSUFFICIENT_INFO:
    'IF_AWARE_HINT_SKIPPED_INSUFFICIENT_INFO',
  IF_REWRITE_DISABLED_ANNOTATION_RISK: 'IF_REWRITE_DISABLED_ANNOTATION_RISK',
  IF_REWRITE_DOUBLE_NOT: 'IF_REWRITE_DOUBLE_NOT',
  IF_REWRITE_SKIPPED_UNEVALUATED: 'IF_REWRITE_SKIPPED_UNEVALUATED',
  MUSTCOVER_INDEX_MISSING: 'MUSTCOVER_INDEX_MISSING',
  NOT_DEPTH_CAPPED: 'NOT_DEPTH_CAPPED',
  OAS_NULLABLE_KEEP_ANNOT: 'OAS_NULLABLE_KEEP_ANNOT',
  ONEOF_SIMPLIFICATION_SKIPPED_UNEVALUATED:
    'ONEOF_SIMPLIFICATION_SKIPPED_UNEVALUATED',
  PNAMES_COMPLEX: 'PNAMES_COMPLEX',
  PNAMES_REWRITE_APPLIED: 'PNAMES_REWRITE_APPLIED',
  RAT_DEN_CAPPED: 'RAT_DEN_CAPPED',
  RAT_FALLBACK_DECIMAL: 'RAT_FALLBACK_DECIMAL',
  RAT_FALLBACK_FLOAT: 'RAT_FALLBACK_FLOAT',
  RAT_LCM_BITS_CAPPED: 'RAT_LCM_BITS_CAPPED',
  REGEX_COMPLEXITY_CAPPED: 'REGEX_COMPLEXITY_CAPPED',
  REGEX_COMPILE_ERROR: 'REGEX_COMPILE_ERROR',
  DRAFT06_PATTERN_TOLERATED: 'DRAFT06_PATTERN_TOLERATED',
  REPAIR_EVAL_GUARD_FAIL: 'REPAIR_EVAL_GUARD_FAIL',
  REPAIR_PNAMES_PATTERN_ENUM: 'REPAIR_PNAMES_PATTERN_ENUM',
  REPAIR_RENAME_PREFLIGHT_FAIL: 'REPAIR_RENAME_PREFLIGHT_FAIL',
  SCHEMA_INTERNAL_REF_MISSING: 'SCHEMA_INTERNAL_REF_MISSING',
  VALIDATION_COMPILE_ERROR: 'VALIDATION_COMPILE_ERROR',
  TRIALS_SKIPPED_COMPLEXITY_CAP: 'TRIALS_SKIPPED_COMPLEXITY_CAP',
  TRIALS_SKIPPED_LARGE_ANYOF: 'TRIALS_SKIPPED_LARGE_ANYOF',
  TRIALS_SKIPPED_LARGE_ONEOF: 'TRIALS_SKIPPED_LARGE_ONEOF',
  TRIALS_SKIPPED_SCORE_ONLY: 'TRIALS_SKIPPED_SCORE_ONLY',
  TARGET_ENUM_NEGATIVE_LOOKAHEADS: 'TARGET_ENUM_NEGATIVE_LOOKAHEADS',
  TARGET_ENUM_ROUNDROBIN_PATTERNPROPS: 'TARGET_ENUM_ROUNDROBIN_PATTERNPROPS',
  UNSAT_AP_FALSE_EMPTY_COVERAGE: 'UNSAT_AP_FALSE_EMPTY_COVERAGE',
  UNSAT_BUDGET_EXHAUSTED: 'UNSAT_BUDGET_EXHAUSTED',
  UNSAT_DEPENDENT_REQUIRED_AP_FALSE: 'UNSAT_DEPENDENT_REQUIRED_AP_FALSE',
  UNSAT_MINPROPERTIES_VS_COVERAGE: 'UNSAT_MINPROPERTIES_VS_COVERAGE',
  UNSAT_MINPROPS_PNAMES: 'UNSAT_MINPROPS_PNAMES',
  UNSAT_PATTERN_PNAMES: 'UNSAT_PATTERN_PNAMES',
  UNSAT_REQUIRED_AP_FALSE: 'UNSAT_REQUIRED_AP_FALSE',
  UNSAT_REQUIRED_VS_PROPERTYNAMES: 'UNSAT_REQUIRED_VS_PROPERTYNAMES',
  UNSAT_REQUIRED_PNAMES: 'UNSAT_REQUIRED_PNAMES',
  UNSAT_NUMERIC_BOUNDS: 'UNSAT_NUMERIC_BOUNDS',
  SOLVER_TIMEOUT: 'SOLVER_TIMEOUT',
  VALIDATION_KEYWORD_FAILED: 'VALIDATION_KEYWORD_FAILED',
} as const;

export const DIAGNOSTIC_CODES = DIAGNOSTIC_CODE_VALUES;

export type KnownDiagnosticCode =
  (typeof DIAGNOSTIC_CODES)[keyof typeof DIAGNOSTIC_CODES];
export type DiagnosticCode = KnownDiagnosticCode | (string & {});

export interface SafeProofCertificate {
  used: boolean;
  finite: boolean;
  states: number;
  witnesses?: string[];
  capsHit?: boolean;
}

export const DIAGNOSTIC_PHASES = {
  NORMALIZE: 'normalize',
  COMPOSE: 'compose',
  GENERATE: 'generate',
  REPAIR: 'repair',
  VALIDATE: 'validate',
} as const;

export type DiagnosticPhase =
  (typeof DIAGNOSTIC_PHASES)[keyof typeof DIAGNOSTIC_PHASES];

const ALL_KNOWN_CODES = new Set<KnownDiagnosticCode>(
  Object.values(DIAGNOSTIC_CODES)
);

const generatorOnlyCodes = new Set<KnownDiagnosticCode>([
  DIAGNOSTIC_CODES.COMPLEXITY_CAP_PATTERNS,
  DIAGNOSTIC_CODES.EXCLUSIVITY_TWEAK_STRING,
  DIAGNOSTIC_CODES.TARGET_ENUM_NEGATIVE_LOOKAHEADS,
  DIAGNOSTIC_CODES.TARGET_ENUM_ROUNDROBIN_PATTERNPROPS,
]);

const composeOnlyCodes = new Set<KnownDiagnosticCode>([
  DIAGNOSTIC_CODES.NAME_AUTOMATON_COMPLEXITY_CAPPED,
  DIAGNOSTIC_CODES.NAME_AUTOMATON_BFS_APPLIED,
  DIAGNOSTIC_CODES.NAME_AUTOMATON_BEAM_APPLIED,
  DIAGNOSTIC_CODES.COMPLEXITY_CAP_ONEOF,
  DIAGNOSTIC_CODES.COMPLEXITY_CAP_ANYOF,
  DIAGNOSTIC_CODES.COMPLEXITY_CAP_ENUM,
  DIAGNOSTIC_CODES.COMPLEXITY_CAP_CONTAINS,
  DIAGNOSTIC_CODES.COMPLEXITY_CAP_SCHEMA_SIZE,
  DIAGNOSTIC_CODES.NAME_AUTOMATON_COMPLEXITY_CAPPED,
  DIAGNOSTIC_CODES.AP_FALSE_UNSAFE_PATTERN,
  DIAGNOSTIC_CODES.AP_FALSE_INTERSECTION_APPROX,
  DIAGNOSTIC_CODES.CONTAINS_UNSAT_BY_SUM,
  DIAGNOSTIC_CODES.CONTAINS_BAG_COMBINED,
  DIAGNOSTIC_CODES.TRIALS_SKIPPED_LARGE_ONEOF,
  DIAGNOSTIC_CODES.TRIALS_SKIPPED_LARGE_ANYOF,
  DIAGNOSTIC_CODES.TRIALS_SKIPPED_SCORE_ONLY,
  DIAGNOSTIC_CODES.TRIALS_SKIPPED_COMPLEXITY_CAP,
  DIAGNOSTIC_CODES.UNSAT_AP_FALSE_EMPTY_COVERAGE,
  DIAGNOSTIC_CODES.UNSAT_MINPROPERTIES_VS_COVERAGE,
  DIAGNOSTIC_CODES.UNSAT_MINPROPS_PNAMES,
  DIAGNOSTIC_CODES.UNSAT_REQUIRED_AP_FALSE,
  DIAGNOSTIC_CODES.UNSAT_REQUIRED_PNAMES,
  DIAGNOSTIC_CODES.UNSAT_REQUIRED_VS_PROPERTYNAMES,
  DIAGNOSTIC_CODES.UNSAT_NUMERIC_BOUNDS,
  DIAGNOSTIC_CODES.SOLVER_TIMEOUT,
]);

const normalizeCodes = new Set<KnownDiagnosticCode>([
  DIAGNOSTIC_CODES.PNAMES_REWRITE_APPLIED,
  DIAGNOSTIC_CODES.PNAMES_COMPLEX,
  DIAGNOSTIC_CODES.ALLOF_SIMPLIFICATION_SKIPPED_UNEVALUATED,
  DIAGNOSTIC_CODES.ANYOF_SIMPLIFICATION_SKIPPED_UNEVALUATED,
  DIAGNOSTIC_CODES.ONEOF_SIMPLIFICATION_SKIPPED_UNEVALUATED,
  DIAGNOSTIC_CODES.IF_REWRITE_DOUBLE_NOT,
  DIAGNOSTIC_CODES.IF_REWRITE_SKIPPED_UNEVALUATED,
  DIAGNOSTIC_CODES.IF_REWRITE_DISABLED_ANNOTATION_RISK,
  DIAGNOSTIC_CODES.OAS_NULLABLE_KEEP_ANNOT,
  DIAGNOSTIC_CODES.DEPENDENCY_GUARDED,
  DIAGNOSTIC_CODES.DYNAMIC_PRESENT,
  DIAGNOSTIC_CODES.NOT_DEPTH_CAPPED,
  DIAGNOSTIC_CODES.DEFS_TARGET_MISSING,
  DIAGNOSTIC_CODES.EXCLMIN_IGNORED_NO_MIN,
  DIAGNOSTIC_CODES.EXCLMAX_IGNORED_NO_MAX,
]);

const repairCodes = new Set<KnownDiagnosticCode>([
  DIAGNOSTIC_CODES.REPAIR_EVAL_GUARD_FAIL,
  DIAGNOSTIC_CODES.REPAIR_PNAMES_PATTERN_ENUM,
  DIAGNOSTIC_CODES.REPAIR_RENAME_PREFLIGHT_FAIL,
]);

const validateCodes = new Set<KnownDiagnosticCode>([
  DIAGNOSTIC_CODES.AJV_FLAGS_MISMATCH,
  DIAGNOSTIC_CODES.EXTERNAL_REF_UNRESOLVED,
  DIAGNOSTIC_CODES.SCHEMA_INTERNAL_REF_MISSING,
  DIAGNOSTIC_CODES.VALIDATION_COMPILE_ERROR,
  DIAGNOSTIC_CODES.VALIDATION_KEYWORD_FAILED,
  DIAGNOSTIC_CODES.DRAFT06_PATTERN_TOLERATED,
]);

const PHASE_ALLOW_LIST = new Map<
  KnownDiagnosticCode,
  ReadonlySet<DiagnosticPhase>
>();

function assignPhases(
  codes: Iterable<KnownDiagnosticCode>,
  ...phases: DiagnosticPhase[]
): void {
  for (const code of codes) {
    const existing = PHASE_ALLOW_LIST.get(code);
    if (existing) {
      const merged = new Set(existing);
      for (const phase of phases) {
        merged.add(phase);
      }
      PHASE_ALLOW_LIST.set(code, merged);
    } else {
      PHASE_ALLOW_LIST.set(code, new Set(phases));
    }
  }
}

assignPhases(generatorOnlyCodes, DIAGNOSTIC_PHASES.GENERATE);
assignPhases(composeOnlyCodes, DIAGNOSTIC_PHASES.COMPOSE);
assignPhases(normalizeCodes, DIAGNOSTIC_PHASES.NORMALIZE);
assignPhases(repairCodes, DIAGNOSTIC_PHASES.REPAIR);
assignPhases(validateCodes, DIAGNOSTIC_PHASES.VALIDATE);
assignPhases(
  [
    DIAGNOSTIC_CODES.REGEX_COMPLEXITY_CAPPED,
    DIAGNOSTIC_CODES.REGEX_COMPILE_ERROR,
  ],
  DIAGNOSTIC_PHASES.NORMALIZE,
  DIAGNOSTIC_PHASES.COMPOSE
);

export function getDiagnosticPhase(
  code: DiagnosticCode
): DiagnosticPhase | undefined {
  if (!isKnownDiagnosticCode(code)) {
    return undefined;
  }

  const allowed = PHASE_ALLOW_LIST.get(code);
  if (!allowed || allowed.size !== 1) {
    return undefined;
  }

  const iterator = allowed.values().next();
  return iterator.done ? undefined : iterator.value;
}

export function isGeneratorOnlyCode(code: DiagnosticCode): boolean {
  return isKnownDiagnosticCode(code) && generatorOnlyCodes.has(code);
}

export function isComposeOnlyCode(code: DiagnosticCode): boolean {
  return isKnownDiagnosticCode(code) && composeOnlyCodes.has(code);
}

export function isKnownDiagnosticCode(
  code: DiagnosticCode
): code is KnownDiagnosticCode {
  return ALL_KNOWN_CODES.has(code as KnownDiagnosticCode);
}

export function getAllowedDiagnosticPhases(
  code: DiagnosticCode
): ReadonlySet<DiagnosticPhase> | undefined {
  if (!isKnownDiagnosticCode(code)) {
    return undefined;
  }

  return PHASE_ALLOW_LIST.get(code);
}
