const DIAGNOSTIC_CODE_VALUES = {
  AP_FALSE_INTERSECTION_APPROX: 'AP_FALSE_INTERSECTION_APPROX',
  AP_FALSE_UNSAFE_PATTERN: 'AP_FALSE_UNSAFE_PATTERN',
  AJV_FLAGS_MISMATCH: 'AJV_FLAGS_MISMATCH',
  ALLOF_SIMPLIFICATION_SKIPPED_UNEVALUATED:
    'ALLOF_SIMPLIFICATION_SKIPPED_UNEVALUATED',
  ANYOF_SIMPLIFICATION_SKIPPED_UNEVALUATED:
    'ANYOF_SIMPLIFICATION_SKIPPED_UNEVALUATED',
  COMPLEXITY_CAP_SCHEMA_SIZE: 'COMPLEXITY_CAP_SCHEMA_SIZE',
  COMPLEXITY_CAP_ANYOF: 'COMPLEXITY_CAP_ANYOF',
  COMPLEXITY_CAP_CONTAINS: 'COMPLEXITY_CAP_CONTAINS',
  COMPLEXITY_CAP_ENUM: 'COMPLEXITY_CAP_ENUM',
  COMPLEXITY_CAP_ONEOF: 'COMPLEXITY_CAP_ONEOF',
  COMPLEXITY_CAP_PATTERNS: 'COMPLEXITY_CAP_PATTERNS',
  CONTAINS_BAG_COMBINED: 'CONTAINS_BAG_COMBINED',
  CONTAINS_NEED_MIN_GT_MAX: 'CONTAINS_NEED_MIN_GT_MAX',
  CONTAINS_UNSAT_BY_SUM: 'CONTAINS_UNSAT_BY_SUM',
  DEFS_TARGET_MISSING: 'DEFS_TARGET_MISSING',
  DEPENDENCY_GUARDED: 'DEPENDENCY_GUARDED',
  DYNAMIC_PRESENT: 'DYNAMIC_PRESENT',
  DYNAMIC_SCOPE_BOUNDED: 'DYNAMIC_SCOPE_BOUNDED',
  EVALTRACE_PROP_SOURCE: 'EVALTRACE_PROP_SOURCE',
  EXCLMAX_IGNORED_NO_MAX: 'EXCLMAX_IGNORED_NO_MAX',
  EXCLMIN_IGNORED_NO_MIN: 'EXCLMIN_IGNORED_NO_MIN',
  EXCLUSIVITY_TWEAK_STRING: 'EXCLUSIVITY_TWEAK_STRING',
  EXTERNAL_REF_UNRESOLVED: 'EXTERNAL_REF_UNRESOLVED',
  IF_AWARE_HINT_APPLIED: 'IF_AWARE_HINT_APPLIED',
  IF_AWARE_HINT_SKIPPED_INSUFFICIENT_INFO:
    'IF_AWARE_HINT_SKIPPED_INSUFFICIENT_INFO',
  IF_REWRITE_DISABLED_ANNOTATION_RISK: 'IF_REWRITE_DISABLED_ANNOTATION_RISK',
  IF_REWRITE_DOUBLE_NOT: 'IF_REWRITE_DOUBLE_NOT',
  IF_REWRITE_SKIPPED_UNEVALUATED: 'IF_REWRITE_SKIPPED_UNEVALUATED',
  MUSTCOVER_INDEX_MISSING: 'MUSTCOVER_INDEX_MISSING',
  NOT_DEPTH_CAPPED: 'NOT_DEPTH_CAPPED',
  OAS_NULLABLE_KEEP_ANNOT: 'OAS_NULLABLE_KEEP_ANNOT',
  ONEOF_SIMPLIFICATION_SKIPPED_UNEVALUATED:
    'ONEOF_SIMPLIFICATION_SKIPPED_UNEVALUATED',
  PNAMES_COMPLEX: 'PNAMES_COMPLEX',
  PNAMES_REWRITE_APPLIED: 'PNAMES_REWRITE_APPLIED',
  RAT_DEN_CAPPED: 'RAT_DEN_CAPPED',
  RAT_FALLBACK_DECIMAL: 'RAT_FALLBACK_DECIMAL',
  RAT_FALLBACK_FLOAT: 'RAT_FALLBACK_FLOAT',
  RAT_LCM_BITS_CAPPED: 'RAT_LCM_BITS_CAPPED',
  REGEX_COMPLEXITY_CAPPED: 'REGEX_COMPLEXITY_CAPPED',
  REGEX_COMPILE_ERROR: 'REGEX_COMPILE_ERROR',
  REPAIR_EVAL_GUARD_FAIL: 'REPAIR_EVAL_GUARD_FAIL',
  REPAIR_PNAMES_PATTERN_ENUM: 'REPAIR_PNAMES_PATTERN_ENUM',
  REPAIR_RENAME_PREFLIGHT_FAIL: 'REPAIR_RENAME_PREFLIGHT_FAIL',
  TRIALS_SKIPPED_COMPLEXITY_CAP: 'TRIALS_SKIPPED_COMPLEXITY_CAP',
  TRIALS_SKIPPED_LARGE_ANYOF: 'TRIALS_SKIPPED_LARGE_ANYOF',
  TRIALS_SKIPPED_LARGE_ONEOF: 'TRIALS_SKIPPED_LARGE_ONEOF',
  TRIALS_SKIPPED_SCORE_ONLY: 'TRIALS_SKIPPED_SCORE_ONLY',
  UNSAT_AP_FALSE_EMPTY_COVERAGE: 'UNSAT_AP_FALSE_EMPTY_COVERAGE',
  UNSAT_BUDGET_EXHAUSTED: 'UNSAT_BUDGET_EXHAUSTED',
  UNSAT_DEPENDENT_REQUIRED_AP_FALSE: 'UNSAT_DEPENDENT_REQUIRED_AP_FALSE',
  UNSAT_MINPROPS_PNAMES: 'UNSAT_MINPROPS_PNAMES',
  UNSAT_PATTERN_PNAMES: 'UNSAT_PATTERN_PNAMES',
  UNSAT_REQUIRED_AP_FALSE: 'UNSAT_REQUIRED_AP_FALSE',
  UNSAT_REQUIRED_PNAMES: 'UNSAT_REQUIRED_PNAMES',
} as const;

export const DIAGNOSTIC_CODES = DIAGNOSTIC_CODE_VALUES;

export type KnownDiagnosticCode =
  (typeof DIAGNOSTIC_CODES)[keyof typeof DIAGNOSTIC_CODES];
export type DiagnosticCode = KnownDiagnosticCode | (string & {});

export const DIAGNOSTIC_PHASES = {
  NORMALIZE: 'normalize',
  COMPOSE: 'compose',
  GENERATE: 'generate',
  REPAIR: 'repair',
  VALIDATE: 'validate',
} as const;

export type DiagnosticPhase =
  (typeof DIAGNOSTIC_PHASES)[keyof typeof DIAGNOSTIC_PHASES];

const ALL_KNOWN_CODES = new Set<KnownDiagnosticCode>(
  Object.values(DIAGNOSTIC_CODES)
);

const generatorOnlyCodes = new Set<KnownDiagnosticCode>([
  DIAGNOSTIC_CODES.COMPLEXITY_CAP_PATTERNS,
  DIAGNOSTIC_CODES.EXCLUSIVITY_TWEAK_STRING,
]);

const composeOnlyCodes = new Set<KnownDiagnosticCode>([
  DIAGNOSTIC_CODES.COMPLEXITY_CAP_ONEOF,
  DIAGNOSTIC_CODES.COMPLEXITY_CAP_ANYOF,
  DIAGNOSTIC_CODES.COMPLEXITY_CAP_ENUM,
  DIAGNOSTIC_CODES.COMPLEXITY_CAP_CONTAINS,
  DIAGNOSTIC_CODES.COMPLEXITY_CAP_SCHEMA_SIZE,
  DIAGNOSTIC_CODES.AP_FALSE_UNSAFE_PATTERN,
  DIAGNOSTIC_CODES.AP_FALSE_INTERSECTION_APPROX,
  DIAGNOSTIC_CODES.CONTAINS_UNSAT_BY_SUM,
  DIAGNOSTIC_CODES.CONTAINS_BAG_COMBINED,
  DIAGNOSTIC_CODES.TRIALS_SKIPPED_LARGE_ONEOF,
  DIAGNOSTIC_CODES.TRIALS_SKIPPED_LARGE_ANYOF,
  DIAGNOSTIC_CODES.TRIALS_SKIPPED_SCORE_ONLY,
  DIAGNOSTIC_CODES.TRIALS_SKIPPED_COMPLEXITY_CAP,
]);

const normalizeCodes = new Set<KnownDiagnosticCode>([
  DIAGNOSTIC_CODES.PNAMES_REWRITE_APPLIED,
  DIAGNOSTIC_CODES.PNAMES_COMPLEX,
  DIAGNOSTIC_CODES.ALLOF_SIMPLIFICATION_SKIPPED_UNEVALUATED,
  DIAGNOSTIC_CODES.ANYOF_SIMPLIFICATION_SKIPPED_UNEVALUATED,
  DIAGNOSTIC_CODES.ONEOF_SIMPLIFICATION_SKIPPED_UNEVALUATED,
  DIAGNOSTIC_CODES.IF_REWRITE_DOUBLE_NOT,
  DIAGNOSTIC_CODES.IF_REWRITE_SKIPPED_UNEVALUATED,
  DIAGNOSTIC_CODES.IF_REWRITE_DISABLED_ANNOTATION_RISK,
  DIAGNOSTIC_CODES.OAS_NULLABLE_KEEP_ANNOT,
  DIAGNOSTIC_CODES.DEPENDENCY_GUARDED,
  DIAGNOSTIC_CODES.DYNAMIC_PRESENT,
  DIAGNOSTIC_CODES.NOT_DEPTH_CAPPED,
  DIAGNOSTIC_CODES.DEFS_TARGET_MISSING,
  DIAGNOSTIC_CODES.EXCLMIN_IGNORED_NO_MIN,
  DIAGNOSTIC_CODES.EXCLMAX_IGNORED_NO_MAX,
]);

const repairCodes = new Set<KnownDiagnosticCode>([
  DIAGNOSTIC_CODES.REPAIR_EVAL_GUARD_FAIL,
  DIAGNOSTIC_CODES.REPAIR_PNAMES_PATTERN_ENUM,
  DIAGNOSTIC_CODES.REPAIR_RENAME_PREFLIGHT_FAIL,
]);

const validateCodes = new Set<KnownDiagnosticCode>([
  DIAGNOSTIC_CODES.AJV_FLAGS_MISMATCH,
  DIAGNOSTIC_CODES.EXTERNAL_REF_UNRESOLVED,
]);

export function getDiagnosticPhase(
  code: DiagnosticCode
): DiagnosticPhase | undefined {
  if (!isKnownDiagnosticCode(code)) {
    return undefined;
  }

  if (generatorOnlyCodes.has(code)) {
    return DIAGNOSTIC_PHASES.GENERATE;
  }

  if (repairCodes.has(code)) {
    return DIAGNOSTIC_PHASES.REPAIR;
  }

  if (validateCodes.has(code)) {
    return DIAGNOSTIC_PHASES.VALIDATE;
  }

  if (composeOnlyCodes.has(code)) {
    return DIAGNOSTIC_PHASES.COMPOSE;
  }

  if (normalizeCodes.has(code)) {
    return DIAGNOSTIC_PHASES.NORMALIZE;
  }

  if (
    code === DIAGNOSTIC_CODES.REGEX_COMPLEXITY_CAPPED ||
    code === DIAGNOSTIC_CODES.REGEX_COMPILE_ERROR
  ) {
    return DIAGNOSTIC_PHASES.COMPOSE;
  }

  return undefined;
}

export function isGeneratorOnlyCode(code: DiagnosticCode): boolean {
  return isKnownDiagnosticCode(code) && generatorOnlyCodes.has(code);
}

export function isComposeOnlyCode(code: DiagnosticCode): boolean {
  return isKnownDiagnosticCode(code) && composeOnlyCodes.has(code);
}

export function isKnownDiagnosticCode(
  code: DiagnosticCode
): code is KnownDiagnosticCode {
  return ALL_KNOWN_CODES.has(code as KnownDiagnosticCode);
}
